const products = [
  {
    id: 1,
    image: "./asset/images/product_2.jpg",
    category: "SOFA",
    product__name: "Oda ottoman",
    product__price: " $699.00",
    data_category: "seating",
  },
  {
    id: 2,
    image: "./asset/images/product_2.jpg",
    category: "DINING CHAR",
    product__name: "Oda ottoman",
    product__price: " $699.00",
    product__selling: "Selling fast",
    product__new: "New",
    data_category: "table",
  },
  {
    id: 3,
    image: "./asset/images/product_3.jpg",
    category: "DINING CHAR",
    product__name: "Oda ottoman",
    product__price__old: "699.00",
    product__price__new: "699.00",
    data_category: "seating",
  },
  {
    id: 4,
    image: "./asset/images/product_4.jpg",
    category: "SOFA",
    product__name: "Oda ottoman",
    product__price: " $699.00",
    data_category: "storage",
  },
  {
    id: 5,
    image: "./asset/images/product_5.jpg",
    category: "SOFA",
    product__name: "Oda ottoman",
    product__price: " $699.00",
    data_category: "lighting",
  },
  {
    id: 6,
    image: "./asset/images/product_5.jpg",
    category: "SOFA",
    product__name: "Oda ottoman",
    product__price: " $699.00",
    product__voucher: "-30%",
    data_category: "seating",
  },
  {
    id: 7,
    image: "./asset/images/product_5.jpg",
    category: "SOFA",
    product__name: "Oda ottoman",
    product__price: " $699.00",
    product__voucher: "-30%",
    data_category: "lighting",
  },
  {
    id: 8,
    image: "./asset/images/product_5.jpg",
    category: "SOFA",
    product__name: "Oda ottoman",
    product__price: " $699.00",
    product__voucher: "-30%",
    data_category: "seating",
  },
  {
    id: 9,
    image: "./asset/images/product_5.jpg",
    category: "SOFA",
    product__name: "Oda ottoman",
    product__price: " $699.00",
    product__voucher: "-30%",
    data_category: "seating",
  },
  {
    id: 10,
    image: "./asset/images/product_5.jpg",
    category: "SOFA",
    product__name: "Oda ottoman",
    product__price: " $699.00",
    product__voucher: "-30%",
    data_category: "storage",
  },
  {
    id: 11,
    image: "./asset/images/product_5.jpg",
    category: "SOFA",
    product__name: "Oda ottoman",
    product__price: " $699.00",
    product__voucher: "-30%",
    data_category: "table",
  },
  {
    id: 12,
    image: "./asset/images/product_5.jpg",
    category: "SOFA",
    product__name: "Oda ottoman",
    product__price: " $699.00",
    product__voucher: "-30%",
    data_category: "table",
  },
];

export default products;
