const products__all__list = [
  {
    data_category: "",
    item: [
      {
        id: 1,
        image: "../asset/images/product_1.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 2,
        image: "../asset/images/product_2.jpg",
        category: "DINING CHAR",
        product__name: "Oda ottoman",
        product__price: " $699.00",
        product__selling: "Selling fast",
        product__new: "New",
      },
      {
        id: 3,
        image: "../asset/images/product_3.jpg",
        category: "DINING CHAR",
        product__name: "Oda ottoman",
        product__price__old: "699.00",
        product__price__new: "699.00",
      },
      {
        id: 4,
        image: "../asset/images/product_4.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 5,
        image: "../asset/images/product_5.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 6,
        image: "../asset/images/product_6.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
        product__voucher: "-30%",
      },
    ],
  },
  {
    data_category: "seating",
    item: [
      {
        id: 1,
        image: "../asset/images/product_1.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 2,
        image: "../asset/images/product_1.jpg",
        category: "DINING CHAR",
        product__name: "Oda ottoman",
        product__price: " $699.00",
        product__selling: "Selling fast",
        product__new: "New",
      },
      {
        id: 3,
        image: "../asset/images/product_3.jpg",
        category: "DINING CHAR",
        product__name: "Oda ottoman",
        product__price__old: "699.00",
        product__price__new: "699.00",
      },
      {
        id: 4,
        image: "../asset/images/product_4.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 5,
        image: "../asset/images/product_5.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 6,
        image: "../asset/images/product_6.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
        product__voucher: "-30%",
      },
      {
        id: 7,
        image: "../asset/images/product_6.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
        product__voucher: "-30%",
      },
      {
        id: 8,
        image: "../asset/images/product_5.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 9,
        image: "../asset/images/product_6.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
        product__voucher: "-30%",
      },
      {
        id: 10,
        image: "../asset/images/product_6.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
        product__voucher: "-30%",
      },
    ],
  },
  {
    data_category: "table",
    item: [
      {
        id: 1,
        image: "../asset/images/product_1.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 2,
        image: "../asset/images/product_2.jpg",
        category: "DINING CHAR",
        product__name: "Oda ottoman",
        product__price: " $699.00",
        product__selling: "Selling fast",
        product__new: "New",
      },
      {
        id: 3,
        image: "../asset/images/product_3.jpg",
        category: "DINING CHAR",
        product__name: "Oda ottoman",
        product__price__old: "699.00",
        product__price__new: "699.00",
      },
      {
        id: 4,
        image: "../asset/images/product_4.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 5,
        image: "../asset/images/product_5.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 6,
        image: "../asset/images/product_6.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
        product__voucher: "-30%",
      },
    ],
  },
  {
    data_category: "storage",
    item: [
      {
        id: 1,
        image: "../asset/images/product_6.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 2,
        image: "../asset/images/product_2.jpg",
        category: "DINING CHAR",
        product__name: "Oda ottoman",
        product__price: " $699.00",
        product__selling: "Selling fast",
        product__new: "New",
      },
      {
        id: 3,
        image: "../asset/images/product_3.jpg",
        category: "DINING CHAR",
        product__name: "Oda ottoman",
        product__price__old: "699.00",
        product__price__new: "699.00",
      },
      {
        id: 4,
        image: "../asset/images/product_4.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 5,
        image: "../asset/images/product_5.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 6,
        image: "../asset/images/product_6.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
        product__voucher: "-30%",
      },
    ],
  },
  {
    data_category: "lighting",
    item: [
      {
        id: 1,
        image: "../asset/images/product_1.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 2,
        image: "../asset/images/product_2.jpg",
        category: "DINING CHAR",
        product__name: "Oda ottoman",
        product__price: " $699.00",
        product__selling: "Selling fast",
        product__new: "New",
      },
      {
        id: 3,
        image: "../asset/images/product_3.jpg",
        category: "DINING CHAR",
        product__name: "Oda ottoman",
        product__price__old: "699.00",
        product__price__new: "699.00",
      },
      {
        id: 4,
        image: "../asset/images/product_4.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 5,
        image: "../asset/images/product_5.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 6,
        image: "../asset/images/product_6.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
        product__voucher: "-30%",
      },
    ],
  },
  {
    data_category: "decor",
    item: [
      {
        id: 1,
        image: "../asset/images/product_1.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 2,
        image: "../asset/images/product_2.jpg",
        category: "DINING CHAR",
        product__name: "Oda ottoman",
        product__price: " $699.00",
        product__selling: "Selling fast",
        product__new: "New",
      },
      {
        id: 3,
        image: "../asset/images/product_3.jpg",
        category: "DINING CHAR",
        product__name: "Oda ottoman",
        product__price__old: "699.00",
        product__price__new: "699.00",
      },
      {
        id: 4,
        image: "../asset/images/product_1.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 5,
        image: "../asset/images/product_6.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
      },
      {
        id: 6,
        image: "../asset/images/product_6.jpg",
        category: "SOFA",
        product__name: "Oda ottoman",
        product__price: " $699.00",
        product__voucher: "-30%",
      },
    ],
  },
];

export default products__all__list;
